<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ArtifactsPivots Condition="'$(ArtifactsPivots)' == ''">$(Configuration)_$(Platform)</ArtifactsPivots>
    <OutDir>$(ArtifactsPath)\bin\$(MSBuildProjectName)\$(ArtifactsPivots)\</OutDir>
    <IntDir>$(ArtifactsPath)\obj\$(MSBuildProjectName)\$(ArtifactsPivots)\</IntDir>
  </PropertyGroup>
</Project>
