#pragma once
// The .cpp files generated by the XamlCompiler unconditionally include the pch.h, so this file must exist, but it does not need to have any content.

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
//#undef GetCurrentTime
