import "ScrollPresenterPrimitives.idl";

namespace Islands.UI.Xaml.Automation.Peers
{

[webhosthidden]
unsealed runtimeclass ScrollPresenterAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    ScrollPresenterAutomationPeer(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter owner);
}

}
