import "ScrollPresenter.idl";
import "ScrollPresenterPrimitives.idl";

namespace Islands.UI.Xaml.Controls.Primitives
{

[webhosthidden]
enum ScrollPresenterViewChangeResult
{
    Completed = 0,
    Interrupted = 1,
    Ignored = 2,
};

[webhosthidden]
runtimeclass ScrollPresenterTestHooksAnchorEvaluatedEventArgs
{
    Double ViewportAnchorPointHorizontalOffset { get; };
    Double ViewportAnchorPointVerticalOffset { get; };
    Windows.UI.Xaml.UIElement AnchorElement { get; };
}

[webhosthidden]
runtimeclass ScrollPresenterTestHooksInteractionSourcesChangedEventArgs
{
    Windows.UI.Composition.Interactions.CompositionInteractionSourceCollection InteractionSources { get; };
}

[webhosthidden]
runtimeclass ScrollPresenterTestHooksExpressionAnimationStatusChangedEventArgs
{
    Boolean IsExpressionAnimationStarted { get; };
    String PropertyName{ get; };
}

[default_interface]
[webhosthidden]
runtimeclass ScrollPresenterTestHooks
{
    static Boolean AreAnchorNotificationsRaised { get; set; };
    static Boolean AreInteractionSourcesNotificationsRaised { get; set; };
    static Boolean AreExpressionAnimationStatusNotificationsRaised { get; set; };
    static Windows.Foundation.IReference<Boolean> IsAnimationsEnabledOverride { get; set; };
    static void GetOffsetsChangeVelocityParameters(out Int32 millisecondsPerUnit, out Int32 minMilliseconds, out Int32 maxMilliseconds);
    static void SetOffsetsChangeVelocityParameters(Int32 millisecondsPerUnit, Int32 minMilliseconds, Int32 maxMilliseconds);
    static void GetZoomFactorChangeVelocityParameters(out Int32 millisecondsPerUnit, out Int32 minMilliseconds, out Int32 maxMilliseconds);
    static void SetZoomFactorChangeVelocityParameters(Int32 millisecondsPerUnit, Int32 minMilliseconds, Int32 maxMilliseconds);
    static void GetContentLayoutOffsetX(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, out Single contentLayoutOffsetX);
    static void SetContentLayoutOffsetX(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Single contentLayoutOffsetX);
    static void GetContentLayoutOffsetY(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, out Single contentLayoutOffsetY);
    static void SetContentLayoutOffsetY(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Single contentLayoutOffsetY);
    static String GetTransformExpressionAnimationExpression(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static void SetTransformExpressionAnimationExpression(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, String transformExpressionAnimationExpression);
    static String GetMinPositionExpressionAnimationExpression(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static void SetMinPositionExpressionAnimationExpression(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, String minPositionExpressionAnimationExpression);
    static String GetMaxPositionExpressionAnimationExpression(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static void SetMaxPositionExpressionAnimationExpression(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, String maxPositionExpressionAnimationExpression);
    static Windows.Foundation.Numerics.Vector2 GetArrangeRenderSizesDelta(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static Windows.Foundation.Numerics.Vector2 GetPosition(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static Windows.Foundation.Numerics.Vector2 GetMinPosition(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static void SetMinPosition(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Windows.Foundation.Numerics.Vector2 minPosition);
    static Windows.Foundation.Numerics.Vector2 GetMaxPosition(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static void SetMaxPosition(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Windows.Foundation.Numerics.Vector2 maxPosition);
    static ScrollPresenterViewChangeResult GetScrollCompletedResult(Islands.UI.Xaml.Controls.ScrollingScrollCompletedEventArgs scrollCompletedEventArgs);
    static ScrollPresenterViewChangeResult GetZoomCompletedResult(Islands.UI.Xaml.Controls.ScrollingZoomCompletedEventArgs zoomCompletedEventArgs);
    static Windows.Foundation.Collections.IVector<Islands.UI.Xaml.Controls.Primitives.ScrollSnapPointBase> GetConsolidatedHorizontalScrollSnapPoints(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static Windows.Foundation.Collections.IVector<Islands.UI.Xaml.Controls.Primitives.ScrollSnapPointBase> GetConsolidatedVerticalScrollSnapPoints(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static Windows.Foundation.Collections.IVector<Islands.UI.Xaml.Controls.Primitives.ZoomSnapPointBase> GetConsolidatedZoomSnapPoints(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter);
    static Windows.Foundation.Numerics.Vector2 GetHorizontalSnapPointActualApplicableZone(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Islands.UI.Xaml.Controls.Primitives.ScrollSnapPointBase scrollSnapPoint);
    static Windows.Foundation.Numerics.Vector2 GetVerticalSnapPointActualApplicableZone(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Islands.UI.Xaml.Controls.Primitives.ScrollSnapPointBase scrollSnapPoint);
    static Windows.Foundation.Numerics.Vector2 GetZoomSnapPointActualApplicableZone(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Islands.UI.Xaml.Controls.Primitives.ZoomSnapPointBase zoomSnapPoint);
    static Int32 GetHorizontalSnapPointCombinationCount(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Islands.UI.Xaml.Controls.Primitives.ScrollSnapPointBase scrollSnapPoint);
    static Int32 GetVerticalSnapPointCombinationCount(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Islands.UI.Xaml.Controls.Primitives.ScrollSnapPointBase scrollSnapPoint);
    static Int32 GetZoomSnapPointCombinationCount(Islands.UI.Xaml.Controls.Primitives.ScrollPresenter scrollPresenter, Islands.UI.Xaml.Controls.Primitives.ZoomSnapPointBase zoomSnapPoint);
    static Windows.UI.Color GetSnapPointVisualizationColor(Islands.UI.Xaml.Controls.Primitives.SnapPointBase snapPoint);
    static void SetSnapPointVisualizationColor(Islands.UI.Xaml.Controls.Primitives.SnapPointBase snapPoint, Windows.UI.Color color);
    static event Windows.Foundation.TypedEventHandler<Islands.UI.Xaml.Controls.Primitives.ScrollPresenter, ScrollPresenterTestHooksAnchorEvaluatedEventArgs> AnchorEvaluated;
    static event Windows.Foundation.TypedEventHandler<Islands.UI.Xaml.Controls.Primitives.ScrollPresenter, ScrollPresenterTestHooksInteractionSourcesChangedEventArgs> InteractionSourcesChanged;
    static event Windows.Foundation.TypedEventHandler<Islands.UI.Xaml.Controls.Primitives.ScrollPresenter, ScrollPresenterTestHooksExpressionAnimationStatusChangedEventArgs> ExpressionAnimationStatusChanged;
    static event Windows.Foundation.TypedEventHandler<Islands.UI.Xaml.Controls.Primitives.ScrollPresenter, Object> ContentLayoutOffsetXChanged;
    static event Windows.Foundation.TypedEventHandler<Islands.UI.Xaml.Controls.Primitives.ScrollPresenter, Object> ContentLayoutOffsetYChanged;
}

}
