import "ScrollView.idl";

namespace Islands.UI.Xaml.Controls.Primitives
{

[default_interface]
[webhosthidden]
runtimeclass ScrollViewTestHooks
{
    static Windows.Foundation.IReference<Boolean> GetAutoHideScrollControllers(Islands.UI.Xaml.Controls.ScrollView scrollView);
    static void SetAutoHideScrollControllers(Islands.UI.Xaml.Controls.ScrollView scrollView, Windows.Foundation.IReference<Boolean> value);
}

}
